.TH MICROCODE_CTL "8" "03 Feb 2020" "update-amd-microcode"
.SH NAME
update-amd-microcode \- check and download new AMD microcode
.SH SYNOPSIS
.B update-amd-microcode
[\fI\--no-reload\fR]
.br
.SH DESCRIPTION
.PP
The update-amd-microcode is a script that check if there is a new
microcode data for the AMD CPU.  Eventually it downloads, installs
and loads the new microcode data, used by the microcode_ctl(8)
utility.  There is an optional argument:
.br
.PP
\fB--no-reload\fR After installing the microcode, it dosn't try to
load the new microcode in the CPU.
.PD
.SH EXAMPLE
.TP
update-amd-microcode
checks, and eventually downloads, installs and loads a new microcode.
.SH FILES
.TP
/lib/firmware/amd-ucode/microcode_amd.bin
The default microcode location
.PD
.SH AUTHOR
This utility is written by Frederic Crozat for Mandriva.
.br
.SH "SEE ALSO"
.BR microcode_ctl (8)
