.TH MICROCODE_CTL "8" "17 May 2007" "update-intel-microcode"
.SH NAME
update-intel-microcode \- check and download new intel microcode
.SH SYNOPSIS
.B update-intel-microcode
[\fI\--no-reload\fR]
.br
.SH DESCRIPTION
.PP
The update-intel-microcode is a script that check if there is a new
microcode data for the Intel CPU.  Eventually it downloads, installs
and loads the new microcode data, used by the microcode_ctl(8)
utility.  There is an optional argument:
.br
.PP
\fB--no-reload\fR After installing the microcode, it dosn't try to
load the new microcode in the CPU.
.PD
.SH EXAMPLE
.TP
update-intel-microcode
checks, and eventually downloads, installs and loads a new microcode.
.SH FILES
.TP
/lib/firmware/intel-microcode/intel-microcode.dat
The default microcode location
.PD
.SH AUTHOR
This utility is written by Giacomo Catenazzi for Debian.
.br
.SH "SEE ALSO"
.BR microcode_ctl (8)
